import glob
import os

from openpilot.common.file_chunker import chunk_file, get_chunk_paths

Import('env', 'arch')

chunker_file = File("#common/file_chunker.py")
lenv = env.Clone()

tinygrad_root = env.Dir("#").abspath
tinygrad_files = ["#" + x for x in glob.glob(env.Dir("#tinygrad_repo").relpath + "/**", recursive=True, root_dir=tinygrad_root)
                  if 'pycache' not in x and os.path.isfile(os.path.join(tinygrad_root, x))]

tg_flags = {
  'larch64': 'DEV=QCOM FLOAT16=1 NOLOCALS=1 JIT_BATCH_SIZE=0',
  'Darwin': f'DEV=CPU THREADS=0 HOME={os.path.expanduser("~")}',
}.get(arch, 'DEV=CPU CPU_LLVM=1 THREADS=0')

pythonpath_string = 'PYTHONPATH="${PYTHONPATH}:' + env.Dir("#tinygrad_repo").abspath + '"'
model_base = File("models/lane_marking_fcamera").abspath
onnx_path = model_base + ".onnx"
pkl_path = model_base + "_tinygrad.pkl"
compile_script = File("compile_tinygrad.py").abspath

def estimate_pickle_max_size(onnx_size):
  return 3.0 * onnx_size + 10 * 1024 * 1024

chunk_targets = get_chunk_paths(pkl_path, estimate_pickle_max_size(os.path.getsize(onnx_path)))
compile_node = lenv.Command(
  pkl_path,
  [onnx_path, compile_script] + tinygrad_files + [chunker_file],
  f'{pythonpath_string} {tg_flags} python3 {compile_script} {onnx_path} {pkl_path}',
)

def do_chunk(target, source, env):
  chunk_file(pkl_path, chunk_targets)

lenv.Command(chunk_targets, compile_node, do_chunk)
